name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/01d.png
    - assets/02d.png
    - assets/03d.png
    - assets/04d.png
    - assets/09d.png
    - assets/10d.png
    - assets/11d.png
    - assets/13d.png
    - assets/50d.png

    - assets/01n.png
    - assets/02n.png
    - assets/03n.png
    - assets/04n.png
    - assets/09n.png
    - assets/10n.png
    - assets/11n.png
    - assets/13n.png
    - assets/50n.png
    
